export const elderlyId = 'userId'
export const elderlySSSKey = 'elderlySSSKey'
export const caregiver1SSSKey = 'caregiver1SSSKey'
export const caregiver2SSSKey = 'caregiver2SSSKey'
export const firestoreSSSKey = 'firestoreSSSKey'