export const elderlyId = 'userId'
export const elderlySSSKey = 'elderlySSSKey'
export const caregiver1SSSKey = 'caregiver1SSSKey'
export const caregiver2SSSKey = 'caregiver2SSSKey'
export const firestoreSSSKey = 'firestoreSSSKey'
export const localDBKey = 'localDBKey' //ainda a não ser utilizada
export const elderlyEmail = 'userEmail'
export const elderlyPwd = 'userPwd'
export const elderlyPhone = 'userPhone'